# Generated by Django 4.2.10 on 2025-12-22 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('building', 'Building'), ('ready', 'Ready'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='building', max_length=20)),
                ('inputs_json', models.JSONField(default=dict)),
                ('start_time_utc', models.DateTimeField()),
                ('end_time_utc', models.DateTimeField()),
                ('weather_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('route_quality_score', models.FloatField(default=0)),
                ('total_walking_distance_m', models.IntegerField(default=0)),
                ('clusters_visited', models.IntegerField(default=0)),
                ('optimization_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField()),
                ('place_provider', models.CharField(default='google', max_length=50)),
                ('place_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=200)),
                ('start_time_utc', models.DateTimeField()),
                ('duration_min', models.IntegerField()),
                ('priority', models.CharField(choices=[('must', 'Must See'), ('nice', 'Nice to Have'), ('optional', 'Optional')], default='nice', max_length=20)),
                ('reason_short', models.TextField(blank=True)),
                ('is_indoor', models.BooleanField(blank=True, null=True)),
                ('price_level', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('queue_score', models.IntegerField(default=1)),
                ('crowd_score', models.IntegerField(default=1)),
                ('noise_level', models.IntegerField(default=1)),
                ('is_tourist_trap', models.BooleanField(default=False)),
                ('local_favorite', models.BooleanField(default=False)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('peak_hours', models.JSONField(blank=True, default=list)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('rank_in_cluster', models.IntegerField(default=0)),
                ('open_status_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='plans.plan')),
            ],
            options={
                'ordering': ['plan', 'order_index'],
                'unique_together': {('plan', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='StopHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_place_id', models.CharField(max_length=255)),
                ('previous_name', models.CharField(max_length=255)),
                ('previous_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('previous_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('previous_data_json', models.JSONField(default=dict)),
                ('change_reason', models.CharField(max_length=100)),
                ('was_user_initiated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='plans.stop')),
            ],
        ),
        migrations.CreateModel(
            name='StopFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('love', 'Love'), ('ok', 'OK'), ('no', 'Not for me')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='plans.stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modes_json', models.JSONField(default=dict)),
                ('recommended_mode', models.CharField(max_length=50)),
                ('recommended_duration_sec', models.IntegerField(default=0)),
                ('recommended_distance_m', models.IntegerField(default=0)),
                ('recommended_reason', models.TextField(blank=True)),
                ('ai_pick_reason', models.TextField(blank=True)),
                ('travel_warning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs_from', to='plans.stop')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='plans.plan')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs_to', to='plans.stop')),
            ],
            options={
                'ordering': ['plan', 'from_stop__order_index'],
            },
        ),
    ]
