# Generated by Django 4.2.10 on 2025-12-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='previous_stop_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='swap_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stop',
            name='swapped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
