# Generated by Django 4.2.10 on 2025-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_stop_previous_stop_data_stop_swap_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='confidence_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='confidence_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='swap_count',
            field=models.IntegerField(default=0),
        ),
    ]
