# Generated by Django 4.2.10 on 2025-12-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_confidence_locked_plan_confidence_locked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('swapping', 'Swapping')], default='building', max_length=20),
        ),
    ]
