# Generated by Django 4.2.10 on 2025-12-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
