# Generated by Django 4.2.10 on 2025-12-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_stop_photo_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
