# Generated by Django 4.2.10 on 2025-12-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_stop_reason_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='budget_feeling',
            field=models.CharField(blank=True, choices=[('cheap', 'Cheap'), ('normal', 'Normal'), ('treat_myself', 'Treat Myself')], help_text='Budget preference from user', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='last_error_code',
            field=models.CharField(blank=True, help_text='Error code if plan generation failed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='last_error_context',
            field=models.JSONField(blank=True, help_text='Additional context about error', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='theme',
            field=models.CharField(blank=True, help_text="Optional theme for plan generation (e.g., 'chill_scenic', 'food_tour')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='business_status',
            field=models.CharField(blank=True, help_text='Business status from Google Places', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='open_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Confidence level in open_status determination', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='open_status_at_planned_time',
            field=models.BooleanField(blank=True, help_text='True if open at planned time, False if closed, None if unknown', null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='open_status_reason',
            field=models.CharField(blank=True, help_text="Reason for open_status (e.g., 'periods_check', 'missing_hours')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='opening_hours_json',
            field=models.JSONField(blank=True, help_text='Opening hours data from Google Places', null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='place_types',
            field=models.JSONField(blank=True, help_text='Google Places types array', null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='planned_daypart',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (6am-11am)'), ('midday', 'Midday (11am-3:30pm)'), ('afternoon', 'Afternoon (3:30pm-6:30pm)'), ('evening', 'Evening (6:30pm-10:30pm)'), ('late', 'Late Night (10:30pm-2am)')], help_text='Time of day this stop is planned for', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='popularity',
            field=models.IntegerField(blank=True, help_text='Number of user ratings (user_ratings_total)', null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
