# Generated by Django 4.2.10 on 2025-12-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_plan_budget_feeling_plan_last_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of scoring factors'),
        ),
        migrations.AddField(
            model_name='stop',
            name='when_selection',
            field=models.CharField(choices=[('now', 'Now'), ('later_today', 'Later today'), ('tonight', 'Tonight'), ('tomorrow', 'Tomorrow')], default='now', help_text="User's timing preference (UI only, maps to start_time)", max_length=20),
        ),
        migrations.AddField(
            model_name='stop',
            name='why_now',
            field=models.CharField(blank=True, help_text='Short reason why this stop works right now (max 5 words)', max_length=50, null=True),
        ),
    ]
