# Generated by Django 4.2.10 on 2025-12-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_stop_score_breakdown_stop_when_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='diversity_score',
            field=models.FloatField(blank=True, help_text='Diversity score (0-1, higher is more diverse)', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='generation_method',
            field=models.CharField(choices=[('llm', 'LLM (OpenAI)'), ('fallback', 'Greedy Fallback'), ('today_deterministic', 'TODAY Deterministic')], default='llm', help_text='Method used to generate this plan', max_length=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='llm_attempts',
            field=models.IntegerField(default=0, help_text='Number of LLM attempts (for debugging)'),
        ),
        migrations.AddField(
            model_name='stop',
            name='closed_reason',
            field=models.CharField(blank=True, default='', help_text='Reason why place is closed', max_length=200),
        ),
        migrations.AddField(
            model_name='stop',
            name='closed_warning',
            field=models.BooleanField(default=False, help_text='True if place may be closed'),
        ),
        migrations.AddField(
            model_name='stop',
            name='hours_unknown',
            field=models.BooleanField(default=False, help_text='True if hours unknown'),
        ),
        migrations.AddField(
            model_name='stop',
            name='slot_role',
            field=models.CharField(blank=True, choices=[('anchor', 'Anchor - Confidence builder'), ('reward', 'Reward - Main attraction'), ('optional', 'Optional - Nice to have')], help_text='Slot role in plan structure', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='open_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=500),
        ),
    ]
