# Generated by Django 4.2.10 on 2025-12-30 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0010_plan_diversity_score_plan_generation_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(help_text='Google Place ID', max_length=255)),
                ('name', models.CharField(help_text='Place name', max_length=255)),
                ('lat', models.DecimalField(decimal_places=7, help_text='Latitude', max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, help_text='Longitude', max_digits=10)),
                ('category', models.CharField(blank=True, help_text='Category (cafe, restaurant, etc.)', max_length=50)),
                ('photo_reference', models.CharField(blank=True, help_text='Google photo reference', max_length=500, null=True)),
                ('rating', models.FloatField(blank=True, help_text='Google rating', null=True)),
                ('price_level', models.IntegerField(blank=True, help_text='Price level (1-4)', null=True)),
                ('vicinity', models.CharField(blank=True, help_text='Address/vicinity', max_length=500)),
                ('notes', models.TextField(blank=True, help_text="User's personal notes about this place")),
                ('tags', models.JSONField(blank=True, default=list, help_text="User's custom tags")),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When user saved this place')),
                ('visited', models.BooleanField(default=False, help_text='Has user visited this place?')),
                ('visited_at', models.DateTimeField(blank=True, help_text='When user visited', null=True)),
                ('saved_from_plan', models.ForeignKey(blank=True, help_text='Plan where user discovered this place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_places_from_here', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='plans_saved_user_id_b2bff0_idx'), models.Index(fields=['user', 'place_id'], name='plans_saved_user_id_82f3d2_idx')],
                'unique_together': {('user', 'place_id')},
            },
        ),
    ]
