# Generated by Django 4.2.10 on 2026-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_savedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_timezone',
            field=models.CharField(default='Europe/Berlin', help_text='Timezone of the plan (city timezone)', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='timing_intent',
            field=models.CharField(choices=[('now', 'Now'), ('later', 'Later'), ('plan_ahead', 'Plan Ahead')], default='now', help_text="User's timing preference", max_length=20),
        ),
    ]
